const appCmdLists = {
  viewtasks: 'cotwork',
  viewtask: 'cotwork',
  addtask: 'cotwork',
  edittask: 'cotwork',
  deletetask: 'cotwork',
  donetask: 'cotwork',
  viewducks: 'cotwork',
  viewduck: 'cotwork',
  rubberduck: 'cotwork',
  cotwork: 'cotwork',
  cookie: 'reppedbot',
  lurk: 'reppedbot',
  twork: 'reppedbot',
  unlurk: 'reppedbot',
  untwork: 'reppedbot',
  lurksquad: 'reppedbot',
  tworksquad: 'reppedbot',
  commands: 'info',
  tip: 'info',
  socials: 'info',
  recipes: 'info',
  food: 'info',
  shop: 'info',
  merch: 'info',
  prime: 'info',
  sub: 'info',
  music: 'info',
  timesheet: 'info',
  discord: 'info',
  codesnax: 'info',
  reppedbot: 'info',

  // reppedbot: 'ai',
  // mutherDucker: [],
  // pomodoro: ['!pom'],
};

module.exports = { appCmdLists };
