const appCmdLists = {
  viewtasks: 'hustle',
  viewtask: 'hustle',
  addtask: 'hustle',
  edittask: 'hustle',
  deletetask: 'hustle',
  donetask: 'hustle',
  viewducks: 'hustle',
  viewduck: 'hustle',
  rubberduck: 'hustle',
  cookie: 'reppedbot',
  lurk: 'reppedbot',
  twork: 'reppedbot',
  unlurk: 'reppedbot',
  untwork: 'reppedbot',
  lurksquad: 'reppedbot',
  tworksquad: 'reppedbot',
  commands: 'info',
  tip: 'info',
  socials: 'info',
  recipes: 'info',
  food: 'info',
  shop: 'info',
  prime: 'info',
  sub: 'info',
  music: 'info',

  // reppedbot: 'ai',
  // mutherDucker: [],
  // pomodoro: ['!pom'],
};

module.exports = { appCmdLists };
